---
title: "Section2 Correlation analysis"
author: "Ye Bi"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: true
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# knitr::opts_knit$set(root.dir = "~/OneDrive - Virginia Tech/Research/Codes/research/RiceUNLMetabolites/Prediction/all_mets/MBLUP")
path.met = "../../../Pheno"
path_trait = "../../../Trait"
```

# Loading packages
```{r, message=F, eval = F}
library(devtools)
library(ggbiplot)
library(pheatmap)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(data.table)
```

# 1. Read metabolite and traits data.
```{r, eval = F}
#change metabolite names
met_names <- read.delim("~/Library/CloudStorage/OneDrive-VirginiaTech/Research/Codes/research/RiceUNLMetabolites/Pheno/raw_data/met_names.txt", header=FALSE)
names <- met_names$V1

met.con <- read.csv(file=file.path(path.met, "met.rr.con.csv")) #192*75
colnames(met.con)[-c(1:2)] = names
met.trt <- read.csv(file=file.path(path.met, "met.rr.trt.csv")) #188*75
colnames(met.trt)[-c(1:2)] = names
load(file=file.path(path_trait, "trait.con.Rdata"))
load(file=file.path(path_trait, "trait.trt.Rdata"))
```


# 2. Heatmap among metabolites 
```{r, eval=F}
#Control grgoup
cor_con = cor(met.con[,-c(1:2)])
g1 = melt(cor_con); colnames(g1) = c("Metabolite1", "Metabolite2", "value")
p1 = ggplot(g1, aes(x = Metabolite1, y = Metabolite2, fill=value)) +
  geom_tile() + 
  coord_fixed() +
  scale_fill_distiller(palette = 'PiYG', limits = c(-0.5,1)) +
  ggtitle("(A)") + 
  xlab("Metabolite")+
  ylab("Metabolite")+
  theme(plot.title = element_text(size=18, face = "bold", hjust = 0), 
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16),
        axis.text.x = element_text(size = 6, angle = 90,hjust=0.95,vjust=0.2), 
        axis.text.y = element_text(size = 6))
print(p1)
dev.print(pdf, file="./heatmap_control_met.pdf", height = 10, width = 10)

#HNT stress group
cor_trt = cor(met.trt[,-c(1:2)])
g2 = melt(cor_trt) ;  colnames(g2) = c("Metabolite1", "Metabolite2", "value")
p2 = ggplot(g2, aes(x = Metabolite1, y = Metabolite2, fill=value)) +
  geom_tile() + 
  coord_fixed() +
  scale_fill_distiller(palette = 'PiYG', limits = c(-0.5,1)) +
  ggtitle("(B)")+
  xlab("Metabolite")+
  ylab("Metabolite")+
  theme(plot.title = element_text(size=18, face = "bold", hjust = 0), 
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16),
        axis.text.x = element_text(size = 6, angle = 90,hjust=0.95,vjust=0.2), 
        axis.text.y = element_text(size = 6))
print(p2)
dev.print(pdf, file="./heatmap_stress_met.pdf", height = 10, width = 10)


# Ratio of trt to con
met.con.over <- met.con[met.con$NSFTV_ID %in% met.trt$NSFTV_ID, ]
met.trt.over <- met.trt[met.trt$NSFTV_ID %in% met.con$NSFTV_ID, ]

# all(met.con.over$NSFTV_ID == met.trt.over$NSFTV_ID)

cor_ratio = cor(met.con.over[,-c(1:2)]/met.trt.over[,-c(1:2)])
g4 = melt(cor_ratio) ;  colnames(g4) = c("Metabolite1", "Metabolite2", "value")
p4 = ggplot(g4, aes(x = Metabolite1, y = Metabolite2, fill=value)) +
  geom_tile() + 
  coord_fixed() +
  scale_fill_distiller(palette = 'PiYG', limits=c(-0.8, 1)) +
  ggtitle("")+
  xlab("Metabolite")+
  ylab("Metabolite")+
  theme(plot.title = element_text(size=18, face = "bold", hjust = 0), 
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16),
        axis.text.x = element_text(size = 6, angle = 90,hjust=0.95,vjust=0.2), 
        axis.text.y = element_text(size = 6))
print(p4)
dev.print(pdf, file="./heatmap_ratio_met.pdf", height = 10, width = 10)
```

## 2.1 Summarize correlation coefficients
### 2.1.1 Control group
```{r, eval=F}
#Control group
summary(g1$value)
met_con_heatmap <- g1[abs(g1$value)>0.9 & abs(g1$value)<1, ]
dim(met_con_heatmap) 
write.csv(met_con_heatmap, "./met_con_heatmap.csv", row.names = F, quote = F)
```

### 2.1.2 Stress group
```{r, eval=F}
met_trt_heatmap <- g2[abs(g2$value)>0.9 & abs(g2$value) <1, ]
dim(met_trt_heatmap) 
write.csv(met_trt_heatmap, "./met_trt_heatmap.csv", row.names = F, quote = F)
```

### 2.1.3 Ratio of stress to control
```{r, eval=F}
met_ratio_heatmap <- g4[abs(g4$value) > 0.9 & abs(g4$value) <1, ]
dim(met_ratio_heatmap) 
write.csv(met_ratio_heatmap, "./met_ratio_hatmap.csv", row.names = F, quote = F)
```

# 3. Heatmap for traits v.s. metabolites
```{r,eval=F}
heatmap_met_trait_func <- function(met, traits, treatment,tt){
    # met <- met.con
    # traits <- trait.con[,-c(1:2)]
    met <- met[,-c(1:2)]
    aa = cor(traits$MajorAxis, met)
    bb = cor(traits$MinorAxis, met)
    cc = cor(traits$Perimeter, met)
    cor.trait.met = rbind(aa,bb,cc)
    rownames(cor.trait.met) = c("Grain length", "Grain width", "Grain perimeter")
    g4 = reshape2::melt(cor.trait.met) ; colnames(g4) = c("Phenotype", "Metabolite", "value")
    p4 = ggplot(g4, aes(x = Phenotype, y = Metabolite, fill=value)) +
      geom_tile() + 
      ggtitle(tt) +
      scale_fill_distiller(palette = 'PiYG', limits = c(-0.41,0.41)) +
      theme(plot.title = element_text(size=18, face = "bold", hjust = 0), 
            axis.title.x = element_text(size = 18),
            axis.title.y = element_text(size = 18),
            axis.text.x = element_text(size = 9), 
            axis.text.y = element_text(size = 9))
    print(p4)
    dev.print(pdf, file=paste0("./met.trait.heatmap_", treatment, ".pdf"), height=10,width=10)
    
   return(p4)

}

g4_con <- heatmap_met_trait_func(met.con,trait.con,treatment = "Control", tt="(A)")
g4_trt <- heatmap_met_trait_func(met.trt,trait.trt,treatment = "Stress", tt="(B)")
```

## 3.1 sumamry correlation coefficients
### 3.1.1 Control group
```{r,eval=F}
summary(g4_con$value)
g4_con_heatmap <- g4_con[abs(g4_con$value)>0.3, ]
dim(g4_con_heatmap) #10
write.csv(g4_con_heatmap, "./trait_met_con_heatmap.csv", row.names = F, quote = F)
```

### 3.1.2 Stress group
```{r,eval=F}
summary(g4_trt$value)
g4_trt_haetmap <- g4_trt[abs(g4_trt$value)>0.3, ]
dim(g4_trt_haetmap) #2
write.csv(g4_trt_haetmap, "./trait_met_trt_heatmap.csv", row.names = F, quote = F)
```

